### ISSUE TITLE
y value of Point returned from onClick is wrong to a certain degree when zooming

### ISSUE THREAD

**Issue by yonatanmgr** [stevenpetryk/mafs#116]
### Steps to reproduce
1. Zoom Mafs component
2. Click on the grid with `onClick={(point, event) => { console.log(point) }`
3. Observe that while the x value is accurate, the y value is wrong

**Comment by zsrobinson** [comment]
Hey there! I wasn't personally able to reproduce this error. Are you using the latest version? Here's the code I used and a screen recording of the expected behavior being demonstrated:

```tsx
<Mafs
  height={788}
  viewBox={{ x: [-1, 7], y: [-5, 5] }}
  zoom
  onClick={(point) => {
    console.log(
      "click",
      "x: " + point[0].toFixed(2),
      "y: " + point[1].toFixed(2)
    );
  }}
>
  <Coordinates.Cartesian />
  {/* ... /*}
</Mafs>
```

https://github.com/stevenpetryk/mafs/assets/82614881/3fcbcbb5-1092-4c4a-a4ba-570615a0e65d

**Comment by stevenpetryk** [comment]
I'll close unless there are more specific reproduction steps.
