### ISSUE TITLE
Latest release (v0.17.0) was not published correctly

### ISSUE THREAD

**Issue by Mesoptier** [stevenpetryk/mafs#123]
The changelog states:

> - Introduces the [LaTeX](https://mafs.dev/guides/experimental/latex) component.
> - Deprecates the `ssr` attribute in favor of never rendering Mafs until hydration.

But it seems the the PR that fixed that last item (#114) was not actually included in the build that was published to NPM. 

You can verify this by checking that the new `MafsCanvas` component does not exist in `build/index.js` on https://www.npmjs.com/package/mafs?activeTab=code.

**Comment by stevenpetryk** [comment]
Thank you! I have no idea why this happened. I'll try to work on some automated tooling to prevent this in the future.

**Comment by Mesoptier** [comment]
In my experience this happens for one of two reasons:
- The `build` script did not run before publishing, so an old build was published. But `build` is included in the `prepublishOnly` script, so that shouldn't be an issue here (though I would use `prepack` instead of `prepublishOnly`).
- The checked out branch was not up to date at the time of publishing. But I don't see how that could've happened either, since the LaTeX component was merged into `main` _after_ #114 was merged.
