### ISSUE TITLE
Vectors not colored correctly

### ISSUE THREAD

**Issue by carrexxii** [stevenpetryk/mafs#137]
Vectors are always drawn with a white outline around the head, regardless of the color:

![Screenshot_20240131_144405](https://github.com/stevenpetryk/mafs/assets/154758622/54709997-206c-40a9-a042-19cf63b5ff86)

**Comment by stevenpetryk** [comment]
Oh dang! Want to take a stab at fixing? It should be pretty easy I think.

**Comment by stevenpetryk** [comment]
Fixed in v0.18.1.
