### ISSUE TITLE
Issue with ES module treatment in Next.js environment

### ISSUE THREAD

**Issue by PavlosDefoort** [stevenpetryk/mafs#147]
Hello! I am currently having an issue when using the Mafs library with Next.js. 

The issue appears to be that in `package.json` of this library the `"type"` is set to `"module"`. However, Next.js treats `.js` files as CommonJS Modules which leads to compatibility issues. I have found a temporary fix in my development environment where I edit the `package.json` to use CommonJS. However, in production, this doesn't work since the `node_modules` folder is typically not committed. I was wondering how Mafs is typically used with Next.js to fix these errors in production.

<img width="717" alt="image" src="https://github.com/stevenpetryk/mafs/assets/123578465/0a27ec23-20ce-4280-a464-8dd729368320">

**Comment by stevenpetryk** [comment]
Huh, I suppose this should get stripped on publish.

**Comment by stevenpetryk** [comment]
I'm a little confused because I'm not able to reproduce the error you're seeing. Can you give a reproduction repo? A fresh Next.js installation works fine in dev and prod for me.

In the meantime, I'll publish a version without `"type": "module"` since it's not really needed.

**Comment by PavlosDefoort** [comment]
> Okay, 0.18.4 was published without `"type": "module"`—give it a whirl. I'll close this issue but let me know if you're still encountering issues.

Thank you so much, it's working now! In terms of reprod repo, I'll see what I can do to reproduce the error myself in a different project, but the project it was occurring in is https://github.com/PavlosDefoort/PhotoProX. Perhaps the issue may be in one of the next js config files.
