### ISSUE TITLE
Discord Channel missed and Mafs.dev can't be accessed

### ISSUE THREAD

**Issue by longlongvip** [stevenpetryk/mafs#154]
Discord Channel missed and Mafs.dev can't be accessed

**Comment by longlongvip** [comment]
> Can't reproduce. 无法重现。

I was in Dsicord's Mafs channel, but suddenly one day, I found out that I was no longer in the channel, and then I tried to go back through the invitation link, but it didn't work

**Comment by stevenpetryk** [comment]
I did ban someone from the server recently for spamming dozens of irrelevant links in quick succession. LLPika or something? 

If that was you, please verify your Discord account is not compromised first, and I will unban you and let you back in with a rate limit.

**Comment by stevenpetryk** [comment]
Understood! I thought you got taken over by a spammer. Unbanned :)
