### ISSUE TITLE
stackblitz mafs's playground is error

### ISSUE THREAD

**Issue by longlongvip** [stevenpetryk/mafs#157]
stackblitz mafs's playground is error
The error is
> Error in /turbo_modules/react@18.3.1/cjs/react.development.js (1630:21)
Cannot read properties of null (reading 'useRef')
![image](https://github.com/stevenpetryk/mafs/assets/35255314/07d3bf88-d1b0-49f9-8ecc-0b5e9f3ba2c1)

**Comment by stevenpetryk** [comment]
Fixed in b88a21dd8261aae5986c1d5b60d0bb4f792073ef
