### ISSUE TITLE
Building mafs error

### ISSUE THREAD

**Issue by zawie** [stevenpetryk/mafs#18]
This is probably due to my inexperience running someone else's react project, and not specifically mafs, however...

Whenever I run the command "yarn start" I always get this error:

<img width="914" alt="Screen Shot 2020-09-30 at 5 59 08 PM" src="https://user-images.githubusercontent.com/15623191/94754642-a4a80180-0346-11eb-846b-31ed1575635d.png">

All I ran was "yarn" before. 

I have some edits I made on my fork of mafs that I want to test before making a pull request. However, I can't test at this injunction!

As a more general issue, it would be nice to include how to setup on the README.

More generically: how do I test my changes before making a pull request!

**Comment by stevenpetryk** [comment]
Based on the error code being 127, I would suspect this might be a permissions issue with the build script. Does running `chmod +x prepublish.sh` and then rerunning fix it?

**Comment by stevenpetryk** [comment]
> As a more general issue, it would be nice to include how to setup on the README.

Definitely—the README needs to be filled in. I have a template I follow for my projects that I'll fill out before wider release. Thanks for bearing with the lack of docs in the meantime ❤️ 

> More generically: how do I test my changes before making a pull request!

There are tests! Just... in the future, not the present. :) To be honest, I've been testing my changes by documenting them: I run `yarn start` in one terminal, and then `yarn docs:start` in another, and go to the Gatsby site that launches. Then I build out an example, put it in the docs, and test it there. That's how I built https://mafs.dev.

**Comment by stevenpetryk** [comment]
I'm going to add a postinstall command to make sure this file is executable. Let me know if this didn't solve your problem so I can continue investigating.
