### ISSUE TITLE
Testing strategy

### ISSUE THREAD

**Issue by stevenpetryk** [stevenpetryk/mafs#20]
I'm trying to think of ways to write tests.

- Snapshot testing could work, but I dislike it. It's flaky to small changes that have no visual effect.
- Screenshot testing might be nice—Mafs is, after all, basically an SVG image. But I wonder if it's slow.
- Interactive elements should have accessibility testing to make sure they're focusable, keyboard operable, etc.

**Comment by stevenpetryk** [comment]
I'm thinking something like https://github.com/americanexpress/jest-image-snapshot would work well here.

**Comment by imrishabh18** [comment]
Hey @stevenpetryk, I have recently started learning testing and would like to contribute to this. Can you let me know how can I help in this?

**Comment by stevenpetryk** [comment]
@imrishabh18 glad you'd like to contribute! I'm setting up a test harness now that allows you to write visual tests, like this:

```tsx
describe("<Circle />", () => {
  it("Renders", async () => {
    expect(
      await renderToImage(
        <>
          <Circle radius={0.25} center={[1, 1]} />
          <Circle radius={0.5} center={[2, 2]} />
          <Circle radius={0.5} center={[3, 3]} color="var(--mafs-blue)" fillOpacity={1} />
          <Circle radius={0.5} center={[4, 4]} color="tomato" strokeStyle="dashed" />
          <Circle radius={0.5} center={[5, 5]} weight={4} />
          <Circle radius={0.5} center={[6, 6]} svgEllipseProps={{ strokeDasharray: "9 10" }} />
        </>
      )
    ).toMatchImageSnapshot()
  })
})
```

And it will render an image like this:

![](https://raw.githubusercontent.com/stevenpetryk/mafs/b6337d2ecf1eea6d87ebf388933ca53511c5d639/src/display/__image_snapshots__/circle-test-tsx-circle-renders-1-snap.png)

And then future test runs will be compared to this image.

**Comment by stevenpetryk** [comment]
Alright @imrishabh18, that PR is merged and I've added a few example tests. Feel free to add more.
