### ISSUE TITLE
Required, but non exported Vector2 Type

### ISSUE THREAD

**Issue by zawie** [stevenpetryk/mafs#22]
Moveable point:
<img width="1406" alt="Screen Shot 2020-10-02 at 12 42 48 AM" src="https://user-images.githubusercontent.com/15623191/94899507-50854600-0448-11eb-9635-d95d46eb8089.png">
Trying to import Vector2:
<img width="1495" alt="Screen Shot 2020-10-02 at 12 50 27 AM" src="https://user-images.githubusercontent.com/15623191/94900101-46177c00-0449-11eb-946f-3d1e45e34c86.png">

I've been playing around implementing mafs in tsx instead of js, however, now that I am using tsx, useMoveablePoint requires a Vector2 type to be passed in, however, mafs doesn't export that type!

**Comment by zawie** [comment]
wait okay so I imported it `import {Vector2} from 'mafs/typings/math', but it takes 4 parameters???

**Comment by stevenpetryk** [comment]
Ah, makes sense that this would be confusing. Vector2 is just an array of the form `[number, number]`, so you don't have to import anything.

Hopefully this can get cleared up when I consolidate all the types, there won't be confusing types that look like they need to be imported (see #15).

**Comment by stevenpetryk** [comment]
In other words, a valid Vector2 is any array of two numbers.

**Comment by stevenpetryk** [comment]
Should be fixed now, thanks to the type rollup.
