### ISSUE TITLE
LaTeX

### ISSUE THREAD

**Issue by stevenpetryk** [stevenpetryk/mafs#4]
LaTeX could be implemented with a number of libraries. I'm partial to [KaTeX](https://katex.org/), and it's what the [original demo page](https://graphing-calculator.netlify.app/) uses, but there are certainly others.

Not sure how sophisticated peoples' LaTeX would get.

Leaving out the integration for now. If anything it'll be implemented as a separate file, like:

```tsx
import { Latex, latex } from "mafs/latex"

<Latex expression={latex`\frac{1}{2}`} />
```

(the `latex` template tag would be a wrapper around String.raw to avoid JavaScript escaping backslashes)

**Comment by amanape** [comment]
I think that KaTeX is the best choice due to its high performance and compatibility with most LaTeX expressions.

```ts
const latex = (strings: TemplateStringsArray, ...values: any[]) => String.raw({ raw: strings }, ...values);

const a = 1;
const b = 2;

const expression = latex`\frac{${a}}{${b}}`;
// expression will be "\frac{1}{2}"
```
```tsx
import { Latex } from "mafs/latex";

<Latex expression={latex`\frac{1}{2}`} />
```

I believe this approach is both simple and effective. I'm willing to try and implement the solution

**Comment by stevenpetryk** [comment]
I love Katex! Feel free to take it on. It will need a `<foreignObject>` I think.

**Comment by PhilippRitzberger** [comment]
I think it would also be nice if we could use the `<Latex ... />` tag as a child of e.g. a `<FuncionGraph ... />` and render it as a description or legend.
I would also be down to implement and help out!

**Comment by stevenpetryk** [comment]
@PhilippRitzberger what would this look like visually? Like the LaTeX would be attached to the graph in some way?
