### ISSUE TITLE
Zooming in on the browser kills framerate on vector field example

### ISSUE THREAD

**Issue by sritchie** [stevenpetryk/mafs#55]
This example is quite fast: https://mafs.dev/guides/display/vector-fields/

But if I pinch zoom, all of the updates become very hitchy and slow. (This is on the latest Brave browser, so I assume Chrome as well.) This does NOT happen on Safari!

![2022-12-08 10 35 15](https://user-images.githubusercontent.com/69635/206523514-5cb5fe68-ed67-40b3-86ef-7ca231df15ee.gif)

**Comment by stevenpetryk** [comment]
Wild! Not much can be done I suspect—seems like a Chromium quirk.
