### ISSUE TITLE
Polar coordinates

### ISSUE THREAD

**Issue by stevenpetryk** [stevenpetryk/mafs#6]
Cartesian coordinates aren't enough—gotta draw some circles too.

**Comment by zawie** [comment]
I presume you don't just want cartesian coordinates to show up, but also to actually be able to plot points using polar coordinates?

**Comment by stevenpetryk** [comment]
I think so. But it would likely be a different component for that. Something like:

```
<Point point={[1, 1]} />
<Point.Polar radius={Math.sqrt(2)} theta={Math.PI / 4} />
```

**Comment by stevenpetryk** [comment]
In other words, I want to keep the coordinate system decoupled from the components as much as I can.

**Comment by zawie** [comment]
how about like:
`<Point.Polar point={[Math.sqrt(2),Math.PI / 4]} />
`
to reduce bulk

**Comment by stevenpetryk** [comment]
You're right—I should keep it as a vector.
