### ISSUE TITLE
To increase margin between nav items

### ISSUE THREAD

**Issue by VenomFate-619** [stevenpetryk/mafs#67]
Need to increase the margin between the nav items because when we hover any item the background colour of the hover item gets coincide  with the background colour of the active item

![image](https://user-images.githubusercontent.com/67755128/210485034-c334b4b0-2811-4e59-98ae-e1c0180d1490.png)

**Comment by stevenpetryk** [comment]
Makes sense to me. Should be a simple matter of taking this `<ul>` in the sidebar and adding `className="flex flex-col gap-1"`. Want to open a PR?

**Comment by stevenpetryk** [comment]
A better way could be to use a wrapper with some padding for each link, so that the interstitial space between links remains clickable. But the `gap-[1px]` method is faster.

**Comment by VenomFate-619** [comment]
Yes, I would like to open a PR.
We can apply margin-bottom to li tags also by adding space-y-2 to ul
