### ISSUE TITLE
babel-loader fails 

### ISSUE THREAD

**Issue by duytk7** [stevenpetryk/mafs#84]
Error:
![Screenshot_1](https://user-images.githubusercontent.com/112994594/212040829-1b17a03b-090d-4762-ab82-cc44d85aea2a.png)
My React app dependencies
![Screenshot_2](https://user-images.githubusercontent.com/112994594/212041152-d7db718c-fdf2-4352-b4f9-e43712e6d475.png)

**Comment by stevenpetryk** [comment]
A modern Babel setup should be able to transpile Mafs' code. I would recommend making sure you're using an up-to-date version of `@babel/preset-env`.
