### ISSUE TITLE
Vector is broken in iOS Safari

### ISSUE THREAD

**Issue by samestep** [stevenpetryk/mafs#95]
Currently the Vectors doc page https://mafs.dev/guides/display/vectors looks like this on my iPhone:

<img height="500px" src="https://user-images.githubusercontent.com/8246041/213608695-8c13e17e-3112-4415-9101-8bc155b7caa0.jpeg" />

**Comment by stevenpetryk** [comment]
Fixed in v0.7.1. Thanks @samestep!

**Comment by samestep** [comment]
That was amazingly fast, thank you @stevenpetryk!
